name: build

on:
  pull_request:
  push:
    tags: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        GOOS:
          - linux
          - windows
          - darwin
        GOARCH:
          - amd64
          - arm64
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: ^1.19
    - name: Build executable
      env:
        GOOS: ${{ matrix.GOOS }}
        GOARCH: ${{ matrix.GOARCH }}
        CGO_ENABLED: 0
      run: |
        go build -buildmode exe -o kojirou.exe kojirou.go
    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: dist-kojirou-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
        path: kojirou.exe
