name: wiki

on:
  push:
    branches:
      - master

jobs:
  wiki:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        repository: ${{ github.repository }}.wiki
        path: wiki
    - uses: actions/setup-go@v3
      with:
        go-version: ^1.19
    - run: |
        rm -rf wiki/*.mediawiki
    - run: |
        go run . --help         > wiki/Home.mediawiki
        go run . --help-ranking > wiki/Ranking.mediawiki
        go run . --help-filter  > wiki/Filtering.mediawiki
    - run: |
        cd wiki
        git config --global user.name  "actions-user"
        git config --global user.email "actions@github.com"
        git add . && git diff-index --quiet HEAD && exit 0
        git commit -m "Add changes" && git push
